#Server port configurations
server:
  port:9191


   #Spring application name
  spring:
  application:
    name:API-GATEWAY
    #Rouring configurations urls should be load balanced
    cloud:
      gateway:
        routes:
          id:USER-SERVICE
        url:lb://USER-SERVICE
        predicates:
          path=/user/**

        id:DEPARTMENT-SERVICE
        url:lb://DEPARTMENT-SERVICE
        predicate:
          path=/department/**


    #configuarations to connect to eureka server to connect the registry
    eureka:
      client:
        register-with-eureka:true
        fetch-registry:true
        service-url:
          defaultZone:http://localhost/8761/eureka
        instance:
          hostname:localhost